### ISSUE TITLE
Drag and drop takes forever

### ISSUE THREAD

**Issue by rololo88** [davidthings/tinyfpga_bx_usbserial#11]
Hello to all, 

 I have a strange issue for a while now on my desktop I7 7700K / 16GB ram. 

 When i try to drag and drop files to desktop it takes sharp 40 seconds to get the file on the desktop. 

 i absolutely have no clue why this happened. I try to scan my computer for virus or malware but no  
 results. Since i use Intel processor, i applied security patches , bios have been updated as well. 

 Maybe this is the issue? No idea to be honest. 

 I it just very annoying, sometimes it is so slow that i had to shut down explorer.exe process and restart it (and it takes also longtime for my desktop to show up again). 

I hope i will get some guidance from the community. 

Thank you in advance for your help. 

Ps: Sorry if i post in the wrong section i am new on github

**Comment by davidthings** [comment]
I think you are in the wrong section of GitHub.
